Upgrade to .NET 6 and using trial versions of Infragistics WPF Nuget packages
brianlagunas/PrismOutlook pull request #4
Opened 2022-08-06 02:13 UTC by vivekrathod

I started learning through your YouTube video series on building the PrismOutlook application (thank you very much for the same). For me, it was convenient to use .NET 6, and also the versions of Infragistics Nuget packages there were paid versions which I did not have access to, so I used the trial versions. I am not sure if this may be of any use to others. In that case, please feel free to drop this PR.

2022-08-08 22:38 UTC, brianlagunas commented
Hey, thanks for the PR. I don't mind accepting this PR, but please remove all references to the tool you used to generate this upgrade.

2022-08-09 02:56 UTC, vivekrathod commented
I removed the references to the tool and the packages it added.

2022-10-31 19:55 UTC, vivekrathod commented
Hi @brianlagunas, if you are busy and just haven't gotten to this yet, I understand. But if there is something I should change/correct, please let me know!

2022-11-01 15:45 UTC, brianlagunas requested changes
Please remove the unnecessary nuget packages

2022-11-01 15:45 UTC, brianlagunas commented on Modules/PrismOutlook.Modules.Calendar/PrismOutlook.Modules.Calendar.csproj
> +    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
remove

2022-11-01 15:45 UTC, brianlagunas commented on Modules/PrismOutlook.Modules.Calendar/PrismOutlook.Modules.Calendar.csproj
> +    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
remove

2022-11-01 15:45 UTC, brianlagunas commented on Modules/PrismOutlook.Modules.Calendar/PrismOutlook.Modules.Calendar.csproj
> +    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
remove

2022-11-01 15:45 UTC, brianlagunas commented on PrismOutlook.Core/PrismOutlook.Core.csproj
> +    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
remove

2022-11-01 15:45 UTC, brianlagunas commented on PrismOutlook.Core/PrismOutlook.Core.csproj
> +    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
remove

2022-11-01 15:45 UTC, brianlagunas commented on PrismOutlook.Core/PrismOutlook.Core.csproj
> +    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
remove

2022-11-01 17:32 UTC, vivekrathod commented
Removed all these NuGet packages you pointed out. 
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />

2022-11-01 17:32 UTC, brianlagunas approved these changes

2022-11-01 17:32 UTC, merged

2022-11-01 17:32 UTC, brianlagunas commented
Thanks for the PR. Sorry it took so long. I completely forgot about this.